'use strict';

import express from 'express';
import cors from 'cors';
import NodeCache from 'node-cache';
import {
    combineData,
    getLatestPriceData,
    getMappingData,
} from './dataUtils.ts';


const app = express();
const port = 8000;

const itemCache = new NodeCache({
    stdTTL: 60,
    checkperiod: 120,
});

const imageCache = new NodeCache({
    stdTTL: 60 * 60 * 24,
    checkperiod: 120,
});

app.use(cors());

app.get('/api/items', async (_req, res) => {
    const cacheKey = `items_data`;
    let combinedData = itemCache.get(cacheKey);

    if (!combinedData) {
        try {
            const [mappingData, latestPriceData] = await Promise.all([
                getMappingData(),
                getLatestPriceData(),
            ]);

            combinedData = combineData(mappingData, latestPriceData);
            console.log('Caching Data');
            itemCache.set(cacheKey, combinedData);
        } catch (err) {
            return res.status(500).json({ error: 'Failed to fetch item data.' });
        }
    } else {
        console.log('Found cached item icons');
    }

    res.status(200).json(combinedData);
});

// Generated by copilot after getting stuck with
// trying to cache item icons
app.get('/api/images/:icon', async (req, res) => {
    const icon = req.params.icon;
    const cacheKey = `image_${icon}`;
    const cachedBuffer = imageCache.get(cacheKey);

    if (cachedBuffer) {
        res.set('Content-Type', 'image/png');
        res.set('Cache-Control', 'public, max-age=86400');
        return res.send(cachedBuffer);
    }

    try {
        const imageUrl = `https://oldschool.runescape.wiki/images/${icon}`;
        const response = await fetch(imageUrl);

        if (!response.ok) {
            return res.sendStatus(502);
        }

        const contentType = response.headers.get('content-type') || 'image/png';
        const arrayBuffer = await response.arrayBuffer();
        const buffer = Buffer.from(arrayBuffer);

        imageCache.set(cacheKey, buffer);
        res.set('Content-Type', contentType);
        res.set('Cache-Control', 'public, max-age=86400');
        res.send(buffer);
    } catch (err) {
        // console.error(err.message);
        res.sendStatus(502);
    }
});

app.listen(port, () => {
    console.log(`Backend running on http://localhost:${port}`);
    console.log('Press Ctrl + C to end the process.');
});
